#!/bin/bash

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
  sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:lukadimnik/dotfiles-linux.git
fi

sudo apt update && sudo apt install vim -y

exit 0
